import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'kn';

const translations = {
  en: {
    welcome: 'Welcome',
    findJobs: 'Find Local Jobs',
    nearbyJobs: 'Nearby Jobs',
    postJob: 'Post a Job',
    profile: 'Profile',
    myJobs: 'My Jobs',
    applications: 'Applications',
    skills: 'Skills',
    location: 'Location',
    phone: 'Phone',
    role: 'Role',
    worker: 'Worker',
    employer: 'Employer',
    apply: 'Apply Now',
    applied: 'Applied',
    title: 'Title',
    description: 'Description',
    payment: 'Payment',
    time: 'Time',
    save: 'Save',
    logout: 'Logout',
    category: 'Category',
    allCategories: 'All Categories',
    delivery: 'Delivery',
    helper: 'Helper',
    mechanic: 'Mechanic',
    cleaner: 'Cleaner',
    repair: 'Repair',
    construction: 'Construction',
    others: 'Others',
    searchPlaceholder: 'Search for jobs, skills...',
    noJobsFound: 'No jobs found nearby.',
    errorLocation: 'Please enable location to see nearby jobs.',
    jobBoard: 'Job Board',
    liveHelp: 'Live Help',
    hireTalent: 'Hire Talent',
    manageOperations: 'Manage your operations',
    topRated: 'Top Rated Professionals',
    urgent: 'Urgent',
    replacementNeeded: 'Replacement Needed',
    pending: 'Pending',
    accepted: 'Accepted',
    rejected: 'Rejected',
    emergencyCancel: 'Emergency Cancel',
    village: 'Village',
    district: 'District',
    state: 'State',
    pincode: 'Pincode',
    appSettings: 'App Settings',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    home: 'Home',
    support: 'Support',
    admin: 'Admin',
    fullName: 'Full Name',
    email: 'Email',
    password: 'Password',
    login: 'Log In',
    signup: 'Sign Up',
    or: 'OR',
    continueWithGoogle: 'Continue with Google',
    noAccount: "Don't have an account? Sign up",
    haveAccount: "Already have an account? Log in",
    loadingApp: 'Loading LocalJob...',
    enableLocation: 'Enable Location',
    locationRationale: 'To show you Jobs within your village and calculate travel distance, LocalJob needs access to your location data. This data is only used while the app is active.',
    allowContinue: 'Allow & Continue',
    magicFill: 'AI Magic Fill',
    workersNeeded: 'Workers Needed Today',
    startTime: 'Start Time',
    endTime: 'End Time',
    salaryPayment: 'Salary / Payment',
    perDay: 'Per Day',
    fixedPrice: 'Fixed Price',
    monthly: 'Monthly',
    postJobNow: 'POST JOB NOW',
    locationDetails: 'Location Details',
    helpCenter: 'Help Center',
    support247: '24/7 support for our community',
    instagramSupport: 'Instagram Support',
    emailSupport: 'Email Support',
    videoTutorials: 'Video Tutorials',
    commonQuestions: 'Common Questions',
    commandCenter: 'Command Center',
    systemOversight: 'System Oversight',
    accounts: 'Accounts',
    market: 'Market',
    settlement: 'Settlement',
    activeMarkets: 'Active Markets',
    totalWorkforce: 'Total Workforce',
    verifiedPros: 'Verified Pros',
    estRevenue: 'Est. Revenue',
    recentActivity: 'Recent Activity',
    clearAll: 'Clear All',
    personalizedForYou: 'Personalized for You'
  },
  hi: {
    welcome: 'स्वागत है',
    findJobs: 'स्थानीय नौकरियां खोजें',
    nearbyJobs: 'आस-पास की नौकरियां',
    postJob: 'नौकरी पोस्ट करें',
    profile: 'प्रोफ़ाइल',
    myJobs: 'मेरी नौकरियां',
    applications: 'आवेदन',
    skills: 'कौशल',
    location: 'स्थान',
    phone: 'फ़ोन',
    role: 'भूमिका',
    worker: 'कामगार',
    employer: 'नियोक्ता',
    apply: 'अभी आवेदन करें',
    applied: 'आवेदन किया',
    title: 'शीर्षक',
    description: 'विवरण',
    payment: 'भुगतान',
    time: 'समय',
    save: 'सहेजें',
    logout: 'लॉगआउट',
    category: 'श्रेणी',
    allCategories: 'सभी श्रेणियां',
    delivery: 'डिलीवरी',
    helper: 'हेल्पर',
    mechanic: 'मैकेनिक',
    cleaner: 'क्लीनर',
    repair: 'मरम्मत',
    construction: 'निर्माण',
    others: 'अन्य',
    searchPlaceholder: 'नौकरियां, कौशल खोजें...',
    noJobsFound: 'आस-पास कोई नौकरी नहीं मिली।',
    errorLocation: 'आस-पास की नौकरियां देखने के लिए स्थान सक्षम करें।',
    jobBoard: 'जॉब बोर्ड',
    liveHelp: 'लाइव मदद',
    hireTalent: 'प्रतिभा को काम पर रखें',
    manageOperations: 'अपने कार्यों का प्रबंधन करें',
    topRated: 'टॉप रेटेड पेशेवर',
    urgent: 'अति आवश्यक',
    replacementNeeded: 'बदलाव की आवश्यकता है',
    pending: 'पेंडिंग',
    accepted: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    emergencyCancel: 'आपातकालीन रद्द',
    village: 'गांव',
    district: 'जिला',
    state: 'राज्य',
    pincode: 'पिनकोड',
    appSettings: 'ऐप सेटिंग्स',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    saveChanges: 'परिवर्तन सहेजें',
    cancel: 'रद्द करें',
    home: 'होम',
    support: 'सहायता',
    admin: 'एडमिन',
    fullName: 'पूरा नाम',
    email: 'ईमेल',
    password: 'पासवर्ड',
    login: 'लॉग इन करें',
    signup: 'साइन अप करें',
    or: 'या',
    continueWithGoogle: 'गूगल के साथ जारी रखें',
    noAccount: "खाता नहीं है? साइन अप करें",
    haveAccount: "पहले से ही एक खाता है? लॉग इन करें",
    loadingApp: 'लोकलजॉब लोड हो रहा है...',
    enableLocation: 'स्थान सक्षम करें',
    locationRationale: 'आपको अपने गांव के भीतर नौकरियां दिखाने और यात्रा की दूरी की गणना करने के लिए, लोकलजॉब को आपके स्थान डेटा तक पहुंच की आवश्यकता है। यह डेटा केवल ऐप के सक्रिय रहने के दौरान ही उपयोग किया जाता है।',
    allowContinue: 'अनुमत दें और जारी रखें',
    magicFill: 'एआई मैजिक फिल',
    workersNeeded: 'आज कामगारों की आवश्यकता है',
    startTime: 'शुरू होने का समय',
    endTime: 'समाप्ति का समय',
    salaryPayment: 'वेतन / भुगतान',
    perDay: 'प्रति दिन',
    fixedPrice: 'नियत मूल्य',
    monthly: 'मासिक',
    postJobNow: 'अब नौकरी पोस्ट करें',
    locationDetails: 'स्थान विवरण',
    helpCenter: 'सहायता केंद्र',
    support247: 'हमारे समुदाय के लिए 24/7 सहायता',
    instagramSupport: 'इंस्टाग्राम सहायता',
    emailSupport: 'ईमेल सहायता',
    videoTutorials: 'वीडियो ट्यूटोरियल',
    commonQuestions: 'सामान्य प्रश्न',
    commandCenter: 'कमांड सेंटर',
    systemOversight: 'सिस्टम ओवरसाइट',
    accounts: 'खाते',
    market: 'मार्केट',
    settlement: 'सेटलमेंट',
    activeMarkets: 'सक्रिय मार्केट',
    totalWorkforce: 'कुल कार्यबल',
    verifiedPros: 'सत्यापित पेशेवर',
    estRevenue: 'अनुमानित राजस्व',
    recentActivity: 'हाल की गतिविधि',
    clearAll: 'सभी साफ करें',
    personalizedForYou: 'आपके लिए व्यक्तिगत'
  },
  kn: {
    welcome: 'ಸ್ವಾಗತ',
    findJobs: 'ಸ್ಥಳೀಯ ಉದ್ಯೋಗಗಳನ್ನು ಹುಡುಕಿ',
    nearbyJobs: 'ಹತ್ತಿರದ ಉದ್ಯೋಗಗಳು',
    postJob: 'ಉದ್ಯೋಗ ಪ್ರಕಟಿಸಿ',
    profile: 'ಪ್ರೊಫೈಲ್',
    myJobs: 'ನನ್ನ ಉದ್ಯೋಗಗಳು',
    applications: 'ಅರ್ಜಿಗಳು',
    skills: 'ಕೌಶಲ್ಯಗಳು',
    location: 'ಸ್ಥಳ',
    phone: 'ಫೋನ್',
    role: 'ಪಾತ್ರ',
    worker: 'ಕೆಲಸಗಾರ',
    employer: 'ಉದ್ಯೋಗದಾತ',
    apply: 'ಈಗಲೇ ಅರ್ಜಿಹಾಕಿ',
    applied: 'ಅರ್ಜಿ ಹಾಕಲಾಗಿದೆ',
    title: 'ಶೀರ್ಷಿಕೆ',
    description: 'ವಿವರಣೆ',
    payment: 'ಪಾವತಿ',
    time: 'ಸಮಯ',
    save: 'ಉಳಿಸಿ',
    logout: 'ನಿರ್ಗಮನ',
    category: 'ವರ್ಗ',
    allCategories: 'ಎಲ್ಲಾ ವರ್ಗಗಳು',
    delivery: 'ಡೆಲಿವರಿ',
    helper: 'ಸಹಾಯಕ',
    mechanic: 'ಮೆಕ್ಯಾನಿಕ್',
    cleaner: 'ಕ್ಲೀನರ್',
    repair: 'ದುರಸ್ತಿ',
    construction: 'ನಿರ್ಮಾಣ',
    others: 'ಇತರೆ',
    searchPlaceholder: 'ಉದ್ಯೋಗಗಳು, ಕೌಶಲ್ಯ ಹುಡುಕಿ...',
    noJobsFound: 'ಹತ್ತಿರದಲ್ಲಿ ಯಾವುದೇ ಉದ್ಯೋಗಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    errorLocation: 'ಹತ್ತಿರದ ಉದ್ಯೋಗಗಳನ್ನು ನೋಡಲು ಸ್ಥಳವನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ.',
    jobBoard: 'ಜಾಬ್ ಬೋರ್ಡ್',
    liveHelp: 'ಲೈವ್ ಸಹಾಯ',
    hireTalent: 'ಪ್ರತಿಭೆಯನ್ನು ನೇಮಿಸಿ',
    manageOperations: 'ನಿಮ್ಮ ಕಾರ್ಯಾಚರಣೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    topRated: 'ಅತ್ಯುತ್ತಮ ವೃತ್ತಿಪರರು',
    urgent: 'ತುರ್ತು',
    replacementNeeded: 'ಬದಲಿ ಅಗತ್ಯವಿದೆ',
    pending: 'ಬಾಕಿ ಇದೆ',
    accepted: 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    rejected: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    emergencyCancel: 'ತುರ್ತು ರದ್ದತಿ',
    village: 'ಹಳ್ಳಿ',
    district: 'ಜಿಲ್ಲೆ',
    state: 'ರಾಜ್ಯ',
    pincode: 'ಪಿನ್ ಕೋಡ್',
    appSettings: 'ಅಪ್ಲಿಕೇಶನ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    editProfile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    home: 'ಮುಖಪುಟ',
    support: 'ಬೆಂಬಲ',
    admin: 'ನಿರ್ವಾಹಕ',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    email: 'ಇಮೇಲ್',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    or: 'ಅಥವಾ',
    continueWithGoogle: 'ಗೂಗಲ್‌ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
    noAccount: "ಖಾತೆ ಇಲ್ಲವೇ? ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    haveAccount: "ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ? ಲಾಗಿನ್ ಮಾಡಿ",
    loadingApp: 'ಲೋಕಲ್‌ಜಾಬ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    enableLocation: 'ಸ್ಥಳವನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
    locationRationale: 'ನಿಮ್ಮ ಹಳ್ಳಿಯೊಳಗಿನ ಉದ್ಯೋಗಗಳನ್ನು ತೋರಿಸಲು ಮತ್ತು ಪ್ರಯಾಣದ ದೂರವನ್ನು ಲೆಕ್ಕಹಾಕಲು, ಲೋಕಲ್‌ಜಾಬ್‌ಗೆ ನಿಮ್ಮ ಸ್ಥಳ ಡೇಟಾದ ಪ್ರವೇಶದ ಅಗತ್ಯವಿದೆ. ಈ ಡೇಟಾವನ್ನು ಅಪ್ಲಿಕೇಶನ್ ಸಕ್ರಿಯವಾಗಿದ್ದಾಗ ಮಾತ್ರ ಬಳಸಲಾಗುತ್ತದೆ.',
    allowContinue: 'ಅನುಮತಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ',
    magicFill: 'AI ಮ್ಯಾಜಿಕ್ ಫಿಲ್',
    workersNeeded: 'ಇಂದು ಅಗತ್ಯವಿರುವ ಕೆಲಸಗಾರರು',
    startTime: 'ಪ್ರಾರಂಭದ ಸಮಯ',
    endTime: 'ಮುಕ್ತಾಯದ ಸಮಯ',
    salaryPayment: 'ಸಂಬಳ / ಪಾವತಿ',
    perDay: 'ಪ್ರತಿದಿನ',
    fixedPrice: 'ಸ್ಥಿರ ಬೆಲೆ',
    monthly: 'ಮಾಸಿಕ',
    postJobNow: 'ಈಗಲೇ ಉದ್ಯೋಗ ಪ್ರಕಟಿಸಿ',
    locationDetails: 'ಸ್ಥಳದ ವಿವರಗಳು',
    helpCenter: 'ಸಹಾಯ ಕೇಂದ್ರ',
    support247: 'ನಮ್ಮ ಸಮುದಾಯಕ್ಕೆ 24/7 ಬೆಂಬಲ',
    instagramSupport: 'ಇನ್‌ಸ್ಟಾಗ್ರಾಮ್ ಬೆಂಬಲ',
    emailSupport: 'ಇಮೇಲ್ ಬೆಂಬಲ',
    videoTutorials: 'ವೀಡಿಯೊ ಟ್ಯುಟೋರಿಯಲ್‌ಗಳು',
    commonQuestions: 'ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು',
    commandCenter: 'ಕಮಾಂಡ್ ಸೆಂಟರ್',
    systemOversight: 'ಸಿಸ್ಟಮ್ ಮೇಲ್ವಿಚಾರಣೆ',
    accounts: 'ಖಾತೆಗಳು',
    market: 'ಮಾರುಕಟ್ಟೆ',
    settlement: 'ಸೆಟಲ್ಮೆಂಟ್',
    activeMarkets: 'ಸಕ್ರಿಯ ಮಾರುಕಟ್ಟೆಗಳು',
    totalWorkforce: 'ಒಟ್ಟು ಕಾರ್ಯಪಡೆ',
    verifiedPros: 'ಪರಿಶೀಲಿಸಿದ ಸಾಧಕರು',
    estRevenue: 'ಅಂದಾಜು ಆದಾಯ',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    clearAll: 'ಎಲ್ಲವನ್ನೂ ಅಳಿಸಿ',
    personalizedForYou: 'ನಿಮಗಾಗಿ ವೈಯಕ್ತೀಕರಿಸಲಾಗಿದೆ'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.en) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: keyof typeof translations.en) => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
